export { ReactComponent as spinner } from './spinner.svg'
export { ReactComponent as exit } from './exit.svg'
export { ReactComponent as back } from './back.svg'
export { ReactComponent as plane } from './plane.svg'
export { ReactComponent as alert } from './alert.svg'
export { ReactComponent as upload } from './upload.svg'
export { ReactComponent as check } from './check.svg'
