name: 'Chromatic'
# the event that will trigger the action
on:
  push:
    branches: [main]

# what the action will do
jobs:
  deploy:
    # the list of steps that the action will go through
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
