name: 'Publish alpha npm package'
on: push

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, '[publish-alpha]') }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
          always-auth: true
      - run: yarn
      - run: yarn build
      - run: yarn publish --tag alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
